- name: Install hostapd and bridge-utils
  package: name={{ item }} state=present
  with_items:
    - hostapd
    - bridge-utils

# Otherwise, wifi authentication often fails because the pi does not
# have enough entropy available!
# source: https://www.raspberrypi.org/forums/viewtopic.php?t=83079
- name: Install rng-tools
  package: name=rng-tools state=present

- name: Enable rng-tools
  service: name=rng-tools enabled=yes state=started

- name: Install hostapd.conf
  template:
    src: hostapd.conf
    dest: /etc/hostapd/hostapd.conf
    mode: 0600
  notify: Reload hostapd

- name: Install /etc/network/interfaces.d/wifi-bridge
  copy:
    src: wifi-bridge
    dest: /etc/network/interfaces.d/wifi-bridge

- name: Enable hostapd in /etc/default/hostapd
  lineinfile:
    line: DAEMON_CONF="/etc/hostapd/hostapd.conf"
    regexp: ^DAEMON_CONF=.*
    insertafter: ^#DAEMON_CONF
    path: /etc/default/hostapd
  notify: Restart hostapd

- name: Make sure hostapd service is enabled&started
  service:
    name: hostapd
    enabled: yes
    state: started

